### ISSUE TITLE
What exactly database.txt is doing?

### ISSUE THREAD

**Issue by thehayat** [nyoungstudios/tf-idf#1]
It's pretty much cool and clean code. But I failed to understand what database.txt is doing. Can You please make it little clear in your Readme.md also is your code removing stop words ?

**Comment by nyoungstudios** [comment]
Yea, so when I read in all the Wikipedia articles (which is maybe 50-100 GB of text) through the readWords.py program, it calculates the IDF (inverse document frequency) part of the algorithm which can take a long time (several hours maybe). It writes the IDF calculation to the database.txt file so that it can easily be read and used in the readDatabase.py program. This means that every time I want to pass an article through this program to calculate the most important words, the readDatabase.py program only has to calculate the TF (term frequency) part of the algorithm (which is very fast), and then we can multiply these together for the final value. This database.txt file saves us the hassle of trying to calculate the IDF part of the algorithm every time. Also, stop words are filtered out by the nature of the algorithm. For example, if there are 10,000 Wikipedia articles (there is much more, but just assume this nice round number for example), and the word "the" appears in 9500 of them. The log(10000/9900)=.00436. This is the IDF part, and when this is multiplied by the TF part, the value is still very small which means it is not determined to be an important word. Since stop words most likely appear in almost all of the Wikipedia articles that we are using to calculate the IDF part, the value approaches zero and anything multiplied by zero is still zero.
